# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            BMS MicroHackathon
tagline:          ''
description:      ''
url:              https://bms-hackathon-2015-09-26.github.io/

author:
  name:           'Daniel Wojda, Łukasz Kamiński'
  url:

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/bms-hackathon-2015-09-26
